In [5]:
import torch

Basics of Maths in Pytorch

In [9]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.empty(size=(3,3)) #Uninitialized Data

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [13]:
print(torch.empty(size=(1,5)).normal_(0,1))
print(torch.empty(size=(1,5)).uniform_(0,1))

tensor([[-0.1181,  0.1104, -0.6610, -0.3780,  0.2698]])
tensor([[0.1043, 0.4239, 0.1864, 0.4729, 0.6489]])


In [14]:
torch.arange(4).bool()

tensor([False,  True,  True,  True])

In [18]:
print(torch.arange(4).short(), ##int16
torch.arange(4).bool(),
torch.arange(4).long(),
torch.arange(4).half())

tensor([0, 1, 2, 3], dtype=torch.int16) tensor([False,  True,  True,  True]) tensor([0, 1, 2, 3]) tensor([0., 1., 2., 3.], dtype=torch.float16)


In [21]:
import numpy as np
torch.from_numpy(np.zeros((5,5)))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [23]:
a=torch.tensor([1,2])
b=torch.tensor([1,2])
z=a+b
print(z)
z=torch.add(a,b)
print(z)

tensor([2, 4])
tensor([2, 4])


In [24]:
torch.true_divide(a,b)

tensor([1., 1.])

the operation followed by '_' is inplace operation.

In [25]:
x=torch.arange(9)
x.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])